import type { ExpoSQLiteDatabase } from 'drizzle-orm/expo-sqlite';
import {
    deleteDailySummary,
    getAverageCaloriesForPreviousDays,
    getDailySummary as getStoredDailySummary,
    getMealsByDate,
    getSetting,
    getUserProfileSettings,
    SETTING_KEYS,
    upsertDailySummary,
} from '../db';
import { parseMealAnalysisValue } from '../utils/mealAnalysis';
import {
    DEFAULT_OPENAI_MODEL,
    getDailySummary as requestDailySummary,
    type DailySummaryMealInput,
} from './openai';
import { getLocalDateString } from '../utils';

type DB = ExpoSQLiteDatabase;

function parseGoal(value: string | null): number | null {
    if (!value) {
        return null;
    }

    const parsed = parseInt(value, 10);
    return Number.isFinite(parsed) && parsed > 0 ? parsed : null;
}

function getMealTypeLabel(mealType: string, language: string): string {
    const labels = language === 'pl'
        ? {
              breakfast: 'Śniadanie',
              second_breakfast: 'II śniadanie',
              lunch: 'Obiad',
              afternoon_snack: 'Podwieczorek',
              dinner: 'Kolacja',
              snack: 'Przekąska',
          }
        : {
              breakfast: 'Breakfast',
              second_breakfast: 'Second breakfast',
              lunch: 'Lunch',
              afternoon_snack: 'Afternoon snack',
              dinner: 'Dinner',
              snack: 'Snack',
          };

    return labels[mealType as keyof typeof labels] ?? mealType;
}

function getEffectiveCalories(aiAnalysis: string | null, calories: number | null): number | null {
    return calories ?? parseMealAnalysisValue(aiAnalysis).calories;
}

export function shouldAutoGenerateDailySummary(date: string, time: string): boolean {
    return date === getLocalDateString() && time >= '18:00';
}

export async function generateAndStoreDailySummary(
    db: DB,
    date: string,
    apiKey: string,
    language: string,
    model: string = DEFAULT_OPENAI_MODEL,
) {
    const meals = getMealsByDate(db, date)
        .map((meal) => ({
            mealType: getMealTypeLabel(meal.mealType, language),
            mealText: meal.mealText,
            time: meal.time,
            calories: getEffectiveCalories(meal.aiAnalysis, meal.calories),
        }))
        .sort((left, right) => left.time.localeCompare(right.time));

    if (meals.length === 0) {
        deleteDailySummary(db, date);
        return null;
    }

    const totalKcal = meals.reduce(
        (sum, meal) => sum + (meal.calories ?? 0),
        0,
    );

    const caloriesAvailable =
        meals.length > 0 && meals.every((meal) => meal.calories !== null);
    const averageCaloriesLast7Days = getAverageCaloriesForPreviousDays(db, date, 7);
    const calorieGoal = parseGoal(getSetting(db, SETTING_KEYS.DAILY_CALORIE_GOAL));
    const userProfile = getUserProfileSettings(db);

    const content = await requestDailySummary(
        apiKey,
        {
            date,
            meals: meals as DailySummaryMealInput[],
            totalKcal,
            calorieGoal,
            caloriesAvailable,
            averageCaloriesLast7Days,
            userProfile,
        },
        language,
        model,
    );

    return upsertDailySummary(db, date, content);
}

export function getStoredSummaryContent(db: DB, date: string) {
    return getStoredDailySummary(db, date);
}