import BottomSheet, {
    BottomSheetScrollView,
    BottomSheetTextInput,
    BottomSheetView,
} from "@gorhom/bottom-sheet";
import DateTimePicker from "@react-native-community/datetimepicker";
import { Ionicons } from "@expo/vector-icons";
import React, {
    forwardRef,
    useCallback,
    useImperativeHandle,
    useMemo,
    useRef,
    useState,
} from "react";
import {
    Alert,
    Modal,
    SectionList,
    StyleSheet,
    Text,
    TextStyle,
    TouchableOpacity,
    View,
} from "react-native";
import { useTranslation } from "react-i18next";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useDatabase } from "../db/DatabaseProvider";
import { getFavoritesByType } from "../db/favorites";
import {
    createMeal,
    deleteMeal,
    getRecentUniqueMeals,
    updateMeal,
} from "../db/meals";
import type { Favorite, Meal, MealType } from "../db/schema";
import { SETTING_KEYS } from "../db/schema";
import { getSetting } from "../db/settings";
import { analyzeMeal, DEFAULT_OPENAI_MODEL } from "../services/openai";
import {
    generateAndStoreDailySummary,
    shouldAutoGenerateDailySummary,
} from "../services/dailySummary";
import { useTheme } from "../theme";
import {
    parseMealAnalysisValue,
    serializeMealAnalysisValue,
} from "../utils/mealAnalysis";
import {
    getMealTypeForCurrentTime,
    getLocalDateString,
    getLocalTimeString,
} from "../utils";

// ─── Public handle ────────────────────────────────────────────────────────────

export interface MealFormSheetHandle {
    openAdd: (defaultDate?: string) => void;
    openEdit: (meal: Meal) => void;
}

// ─── Props ────────────────────────────────────────────────────────────────────

interface MealFormSheetProps {
    /** Called after a successful save, with the date the meal was saved to. */
    onSaved: (date: string) => void;
}

// ─── Constants ────────────────────────────────────────────────────────────────

const MEAL_TYPES: MealType[] = [
    "breakfast",
    "second_breakfast",
    "lunch",
    "afternoon_snack",
    "dinner",
    "snack",
];

const SNAP_QUICK = 0; // 50% — quick entry
const SNAP_FULL = 1; // 92% — full form
const MAX_SUGGESTIONS_QUICK = 3;
const MAX_SUGGESTIONS_FULL = 7;

/** Sort suggestion strings shortest-first so wrap layout fills rows efficiently. */
function sortChipsByLength(chips: string[]): string[] {
    return [...chips].sort((a, b) => a.length - b.length);
}

// ─── Component ────────────────────────────────────────────────────────────────

export const MealFormSheet = forwardRef<
    MealFormSheetHandle,
    MealFormSheetProps
>(({ onSaved }, ref) => {
    const { t, i18n } = useTranslation();
    const db = useDatabase();
    const { colors, typography, spacing, borderRadius } = useTheme();
    const insets = useSafeAreaInsets();

    const bottomSheetRef = useRef<BottomSheet>(null);
    const snapPoints = useMemo(() => ["50%", "92%"], []);

    // ── Form identity ────────────────────────────────────────────────────────
    const [mode, setMode] = useState<"add" | "edit">("add");
    const [editMealId, setEditMealId] = useState<number | null>(null);
    const [isExpanded, setIsExpanded] = useState(false);

    // ── Field state ──────────────────────────────────────────────────────────
    const [mealText, setMealText] = useState("");
    const [mealComment, setMealComment] = useState("");
    const [mealType, setMealType] = useState<MealType>("snack");
    const [selectedDate, setSelectedDate] = useState(getLocalDateString);
    const [selectedTime, setSelectedTime] = useState(getLocalTimeString);
    const [calories, setCalories] = useState("");
    const [notes, setNotes] = useState("");

    // ── UI state ─────────────────────────────────────────────────────────────
    const [validationError, setValidationError] = useState<string | null>(null);
    const [isSaving, setIsSaving] = useState(false);
    const [isAnalyzing, setIsAnalyzing] = useState(false);
    const [showDatePicker, setShowDatePicker] = useState(false);
    const [showTimePicker, setShowTimePicker] = useState(false);
    const [favoritesSections, setFavoritesSections] = useState<
        Array<{ title: string; data: Favorite[] }>
    >([]);
    const [showFavoritesPicker, setShowFavoritesPicker] = useState(false);
    const [recentSuggestions, setRecentSuggestions] = useState<string[]>([]);
    const [originalAiAnalysisValue, setOriginalAiAnalysisValue] = useState<
        string | null
    >(null);
    const [originalAnalysisText, setOriginalAnalysisText] = useState<
        string | null
    >(null);
    const [
        originalAiAnalysisWasStructured,
        setOriginalAiAnalysisWasStructured,
    ] = useState(false);
    const [originalMealDate, setOriginalMealDate] = useState<string | null>(
        null,
    );
    const [originalMealTime, setOriginalMealTime] = useState<string | null>(
        null,
    );

    // ── Computed suggestions ─────────────────────────────────────────────────
    const filteredSuggestions = useMemo(() => {
        const query = mealText.trim().toLowerCase();
        if (!query) return recentSuggestions;
        return recentSuggestions.filter((s) => s.toLowerCase().includes(query));
    }, [recentSuggestions, mealText]);
    // ── Reset helper ─────────────────────────────────────────────────────────

    const resetForAdd = useCallback(
        (date: string) => {
            const now = new Date();
            setMode("add");
            setEditMealId(null);
            setMealText("");
            setMealComment("");
            setMealType(getMealTypeForCurrentTime(now));
            setSelectedDate(date);
            setSelectedTime(getLocalTimeString());
            setCalories("");
            setNotes("");
            setOriginalAiAnalysisValue(null);
            setOriginalAnalysisText(null);
            setOriginalAiAnalysisWasStructured(false);
            setOriginalMealDate(null);
            setOriginalMealTime(null);
            setValidationError(null);
            setShowDatePicker(false);
            setShowTimePicker(false);
            setRecentSuggestions(getRecentUniqueMeals(db, 10));
        },
        [db],
    );

    // ── Imperative handle ────────────────────────────────────────────────────

    useImperativeHandle(ref, () => ({
        openAdd: (defaultDate) => {
            resetForAdd(defaultDate ?? getLocalDateString());
            setIsExpanded(false);
            bottomSheetRef.current?.snapToIndex(SNAP_QUICK);
        },
        openEdit: (meal) => {
            const parsedAiAnalysis = parseMealAnalysisValue(meal.aiAnalysis);
            setMode("edit");
            setEditMealId(meal.id);
            setMealText(meal.mealText);
            setMealComment(meal.mealComment ?? "");
            setMealType(meal.mealType as MealType);
            setSelectedDate(meal.date);
            setSelectedTime(meal.time);
            const effectiveCalories =
                meal.calories ?? parsedAiAnalysis.calories;
            setCalories(effectiveCalories?.toString() ?? "");
            setNotes(parsedAiAnalysis.analysis ?? "");
            setOriginalAiAnalysisValue(parsedAiAnalysis.rawValue);
            setOriginalAnalysisText(parsedAiAnalysis.analysis);
            setOriginalAiAnalysisWasStructured(parsedAiAnalysis.isStructured);
            setOriginalMealDate(meal.date);
            setOriginalMealTime(meal.time);
            setValidationError(null);
            setShowDatePicker(false);
            setShowTimePicker(false);
            setRecentSuggestions(getRecentUniqueMeals(db, 10));
            setIsExpanded(true);
            bottomSheetRef.current?.snapToIndex(SNAP_FULL);
        },
    }));

    // ── Sheet event handlers ─────────────────────────────────────────────────

    const handleSheetChange = useCallback((index: number) => {
        if (index === SNAP_QUICK) setIsExpanded(false);
        else if (index === SNAP_FULL) setIsExpanded(true);
    }, []);

    const handleClose = useCallback(() => {
        bottomSheetRef.current?.close();
    }, []);

    const handleExpand = useCallback(() => {
        setIsExpanded(true);
        bottomSheetRef.current?.snapToIndex(SNAP_FULL);
    }, []);

    const handleCollapse = useCallback(() => {
        setIsExpanded(false);
        bottomSheetRef.current?.snapToIndex(SNAP_QUICK);
    }, []);

    const handleSheetClose = useCallback(() => {
        setIsAnalyzing(false);
        setValidationError(null);
        setShowDatePicker(false);
        setShowTimePicker(false);
        setShowFavoritesPicker(false);
    }, []);

    // ── Favorites picker ─────────────────────────────────────────────────────

    const handleOpenFavoritesPicker = useCallback(() => {
        const templates = getFavoritesByType(db, "template");
        const starred = getFavoritesByType(db, "starred");
        const sections: Array<{ title: string; data: Favorite[] }> = [];
        if (templates.length > 0) {
            sections.push({
                title: t("mealForm.favorites_picker_section_templates"),
                data: templates,
            });
        }
        if (starred.length > 0) {
            sections.push({
                title: t("mealForm.favorites_picker_section_starred"),
                data: starred,
            });
        }
        setFavoritesSections(sections);
        setShowFavoritesPicker(true);
    }, [db, t]);

    const handlePickFavorite = useCallback(
        (fav: Favorite) => {
            setMealText(fav.mealText);
            if (fav.calories != null) {
                setCalories(fav.calories.toString());
            }
            if (validationError) {
                setValidationError(null);
            }
            setShowFavoritesPicker(false);
        },
        [validationError],
    );

    const handlePickSuggestion = useCallback(
        (suggestion: string) => {
            setMealText(suggestion);
            if (validationError) {
                setValidationError(null);
            }
        },
        [validationError],
    );

    const triggerAutoDailySummaries = useCallback(
        (
            entries: Array<{ date: string | null; time: string | null }>,
            apiKey: string,
            model: string,
        ) => {
            const datesToRefresh = new Set<string>();

            for (const entry of entries) {
                if (
                    entry.date &&
                    entry.time &&
                    shouldAutoGenerateDailySummary(entry.date, entry.time)
                ) {
                    datesToRefresh.add(entry.date);
                }
            }

            datesToRefresh.forEach((date) => {
                generateAndStoreDailySummary(
                    db,
                    date,
                    apiKey,
                    i18n.language ?? "en",
                    model,
                )
                    .then(() => {
                        onSaved(date);
                    })
                    .catch((error: unknown) => {
                        console.warn("Auto daily summary failed:", error);
                    });
            });
        },
        [db, i18n.language, onSaved],
    );

    // ── Save ─────────────────────────────────────────────────────────────────

    const handleSave = useCallback(() => {
        const trimmed = mealText.trim();
        if (!trimmed) {
            setValidationError(t("mealForm.validation_required"));
            return;
        }

        setIsSaving(true);
        let savedMealId: number | null = null;
        let savedDate = selectedDate;
        let savedCalories: number | null = null;
        let savedNotes: string | null = null;
        let savedComment: string | null = null;

        try {
            const rawCalories = calories.trim()
                ? parseInt(calories.trim(), 10)
                : null;
            const cleanCalories =
                rawCalories !== null && !isNaN(rawCalories)
                    ? rawCalories
                    : null;
            const cleanNotes = notes.trim() || null;
            const cleanComment = mealComment.trim() || null;
            const originalStructuredAnalysis =
                originalAiAnalysisWasStructured && originalAiAnalysisValue
                    ? parseMealAnalysisValue(originalAiAnalysisValue)
                    : null;
            const shouldPreserveOriginalStructuredValue =
                mode === "edit" &&
                originalStructuredAnalysis?.isStructured &&
                cleanNotes === originalAnalysisText &&
                cleanCalories === originalStructuredAnalysis.calories;
            const nextAiAnalysisValue = shouldPreserveOriginalStructuredValue
                ? originalAiAnalysisValue
                : mode === "edit" && originalStructuredAnalysis?.isStructured
                  ? serializeMealAnalysisValue({
                        analysis: cleanNotes,
                        calories: cleanCalories,
                        ingredients: originalStructuredAnalysis.ingredients,
                    })
                  : cleanNotes;
            savedCalories = cleanCalories;
            savedNotes = cleanNotes;
            savedComment = cleanComment;

            if (mode === "add") {
                const created = createMeal(db, {
                    date: selectedDate,
                    time: selectedTime,
                    mealType,
                    mealText: trimmed,
                    mealComment: cleanComment,
                    calories: cleanCalories,
                    aiAnalysis: nextAiAnalysisValue,
                });
                savedMealId = created.id;
            } else if (editMealId !== null) {
                updateMeal(db, editMealId, {
                    date: selectedDate,
                    time: selectedTime,
                    mealType,
                    mealText: trimmed,
                    mealComment: cleanComment,
                    calories: cleanCalories,
                    aiAnalysis: nextAiAnalysisValue,
                });
                savedMealId = editMealId;
            }
        } catch (error) {
            console.error("Failed to save meal:", error);
            setValidationError(t("mealForm.save_error"));
            setIsSaving(false);
            return;
        }

        setIsSaving(false);

        // Check if AI enrichment is applicable:
        // - API key must be set
        // - At least one of calories or aiAnalysis must be empty
        const apiKey = (() => {
            try {
                return getSetting(db, SETTING_KEYS.OPENAI_API_KEY);
            } catch {
                return null;
            }
        })();
        const model = (() => {
            try {
                return (
                    getSetting(db, SETTING_KEYS.OPENAI_MODEL) ??
                    DEFAULT_OPENAI_MODEL
                );
            } catch {
                return DEFAULT_OPENAI_MODEL;
            }
        })();
        const hasApiKey = Boolean(apiKey && apiKey.trim() !== "");
        const needsAiOnAdd =
            hasApiKey &&
            savedMealId !== null &&
            mode === "add" &&
            (savedCalories === null || savedNotes === null);
        const canReAnalyzeOnEdit =
            hasApiKey && savedMealId !== null && mode === "edit";
        const shouldAutoSummary =
            hasApiKey && (mode === "add" || mode === "edit");

        if (canReAnalyzeOnEdit) {
            // Ask user whether to re-run AI analysis on the edited meal
            Alert.alert(
                t("mealForm.reanalyze_title"),
                t("mealForm.reanalyze_message"),
                [
                    {
                        text: t("mealForm.reanalyze_no"),
                        style: "cancel",
                        onPress: () => {
                            bottomSheetRef.current?.close();
                            onSaved(savedDate);
                            if (shouldAutoSummary && apiKey) {
                                triggerAutoDailySummaries(
                                    [
                                        { date: savedDate, time: selectedTime },
                                        {
                                            date: originalMealDate,
                                            time: originalMealTime,
                                        },
                                    ],
                                    apiKey,
                                    model,
                                );
                            }
                        },
                    },
                    {
                        text: t("mealForm.reanalyze_yes"),
                        onPress: () => {
                            const mealIdForReAnalysis = savedMealId!;
                            setIsAnalyzing(true);
                            analyzeMeal(
                                apiKey!,
                                trimmed,
                                i18n.language ?? "en",
                                model,
                                savedComment,
                            )
                                .then((result) => {
                                    const patch: {
                                        calories?: number | null;
                                        aiAnalysis?: string | null;
                                    } = {};
                                    if (result.calories !== null) {
                                        patch.calories = result.calories;
                                    }
                                    if (
                                        result.ingredients !== null ||
                                        result.analysis !== null
                                    ) {
                                        patch.aiAnalysis =
                                            serializeMealAnalysisValue({
                                                analysis: result.analysis,
                                                calories: result.calories,
                                                ingredients: result.ingredients,
                                            });
                                    }
                                    if (Object.keys(patch).length > 0) {
                                        try {
                                            updateMeal(
                                                db,
                                                mealIdForReAnalysis,
                                                patch,
                                            );
                                        } catch {
                                            // ignore
                                        }
                                    }
                                })
                                .catch((err: unknown) => {
                                    console.warn("AI re-analysis failed:", err);
                                    Alert.alert(
                                        t("mealForm.ai_error_title"),
                                        t("mealForm.ai_error_message"),
                                    );
                                })
                                .finally(() => {
                                    setIsAnalyzing(false);
                                    bottomSheetRef.current?.close();
                                    onSaved(savedDate);
                                    if (shouldAutoSummary && apiKey) {
                                        triggerAutoDailySummaries(
                                            [
                                                {
                                                    date: savedDate,
                                                    time: selectedTime,
                                                },
                                                {
                                                    date: originalMealDate,
                                                    time: originalMealTime,
                                                },
                                            ],
                                            apiKey,
                                            model,
                                        );
                                    }
                                });
                        },
                    },
                ],
            );
            return;
        }

        if (!needsAiOnAdd) {
            bottomSheetRef.current?.close();
            onSaved(savedDate);
            if (shouldAutoSummary && apiKey) {
                triggerAutoDailySummaries(
                    [
                        { date: savedDate, time: selectedTime },
                        { date: originalMealDate, time: originalMealTime },
                    ],
                    apiKey,
                    model,
                );
            }
            return;
        }

        // Run AI enrichment asynchronously, keeping sheet open
        setIsAnalyzing(true);
        const mealIdForAi = savedMealId!;

        analyzeMeal(
            apiKey!,
            trimmed,
            i18n.language ?? "en",
            model,
            savedComment,
        )
            .then((result) => {
                const patch: {
                    calories?: number | null;
                    aiAnalysis?: string | null;
                } = {};
                if (savedCalories === null && result.calories !== null) {
                    patch.calories = result.calories;
                }
                if (
                    result.ingredients !== null ||
                    (savedNotes === null && result.analysis !== null)
                ) {
                    patch.aiAnalysis = serializeMealAnalysisValue({
                        analysis: savedNotes ?? result.analysis,
                        calories: savedCalories ?? result.calories,
                        ingredients: result.ingredients,
                    });
                }
                if (Object.keys(patch).length > 0) {
                    try {
                        updateMeal(db, mealIdForAi, patch);
                    } catch {
                        // ignore — meal already saved
                    }
                }
            })
            .catch((err: unknown) => {
                console.warn("AI analysis failed:", err);
                Alert.alert(
                    t("mealForm.ai_error_title"),
                    t("mealForm.ai_error_message"),
                );
            })
            .finally(() => {
                setIsAnalyzing(false);
                bottomSheetRef.current?.close();
                onSaved(savedDate);
                if (shouldAutoSummary && apiKey) {
                    triggerAutoDailySummaries(
                        [
                            { date: savedDate, time: selectedTime },
                            { date: originalMealDate, time: originalMealTime },
                        ],
                        apiKey,
                        model,
                    );
                }
            });
    }, [
        mealText,
        mealComment,
        calories,
        notes,
        mode,
        editMealId,
        selectedDate,
        selectedTime,
        mealType,
        db,
        onSaved,
        t,
        i18n.language,
        originalAiAnalysisValue,
        originalAiAnalysisWasStructured,
        originalAnalysisText,
        originalMealDate,
        originalMealTime,
        triggerAutoDailySummaries,
    ]);

    const handleDelete = useCallback(() => {
        if (editMealId === null) {
            return;
        }

        Alert.alert(
            t("mealForm.delete_confirm_title"),
            t("mealForm.delete_confirm_message"),
            [
                {
                    text: t("mealForm.delete_confirm_cancel"),
                    style: "cancel",
                },
                {
                    text: t("mealForm.delete_confirm_ok"),
                    style: "destructive",
                    onPress: () => {
                        try {
                            deleteMeal(db, editMealId);
                            bottomSheetRef.current?.close();
                            onSaved(selectedDate);
                        } catch (error) {
                            console.error("Failed to delete meal:", error);
                            setValidationError(t("mealForm.delete_error"));
                        }
                    },
                },
            ],
        );
    }, [db, editMealId, onSaved, selectedDate, t]);

    // ── Date/time picker handlers ────────────────────────────────────────────

    const handleDateChange = useCallback((_: unknown, date?: Date) => {
        setShowDatePicker(false);
        if (date) {
            const y = date.getFullYear();
            const m = String(date.getMonth() + 1).padStart(2, "0");
            const d = String(date.getDate()).padStart(2, "0");
            setSelectedDate(`${y}-${m}-${d}`);
        }
    }, []);

    const handleTimeChange = useCallback((_: unknown, time?: Date) => {
        setShowTimePicker(false);
        if (time) {
            const h = String(time.getHours()).padStart(2, "0");
            const m = String(time.getMinutes()).padStart(2, "0");
            setSelectedTime(`${h}:${m}`);
        }
    }, []);

    const datePickerValue = useMemo(() => {
        const parts = selectedDate.split("-");
        if (parts.length === 3) {
            return new Date(+parts[0], +parts[1] - 1, +parts[2]);
        }
        return new Date();
    }, [selectedDate]);

    const timePickerValue = useMemo(() => {
        const d = new Date();
        const parts = selectedTime.split(":");
        if (parts.length === 2) {
            d.setHours(+parts[0], +parts[1], 0, 0);
        }
        return d;
    }, [selectedTime]);

    // ── Display helpers ──────────────────────────────────────────────────────

    const formatDisplayDate = (dateStr: string) => {
        const parts = dateStr.split("-");
        if (parts.length !== 3) return dateStr;
        return `${parts[2]}.${parts[1]}.${parts[0]}`;
    };

    // ── Shared computed styles ───────────────────────────────────────────────

    const sectionLabel = useMemo(
        () => ({
            color: colors.textSecondary,
            fontSize: typography.fontSize.sm,
            fontWeight: typography.fontWeight.semiBold,
            marginBottom: spacing.xs,
            textTransform: "uppercase" as const,
            letterSpacing: 0.5 as const,
        }),
        [colors, typography, spacing],
    );

    const fieldRowButton = useMemo(
        () => ({
            backgroundColor: colors.inputBackground,
            borderColor: colors.inputBorder,
            borderWidth: 1,
            borderRadius: borderRadius.md,
            paddingHorizontal: spacing.md,
            paddingVertical: spacing.md,
            flexDirection: "row" as const,
            alignItems: "center" as const,
            gap: spacing.sm,
        }),
        [colors, borderRadius, spacing],
    );

    const chipFor = useCallback(
        (selected: boolean) => ({
            paddingHorizontal: spacing.md,
            paddingVertical: spacing.sm,
            borderRadius: borderRadius.full,
            backgroundColor: selected ? colors.primary : colors.surface,
            borderWidth: 1,
            borderColor: selected ? colors.primary : colors.border,
            margin: 3,
        }),
        [colors, borderRadius, spacing],
    );

    const suggestionScrollContent = useMemo(
        () => ({
            flexDirection: "row" as const,
            flexWrap: "wrap" as const,
            paddingVertical: spacing.xs,
        }),
        [spacing],
    );

    const suggestionChipStyle = useMemo(
        () => ({
            backgroundColor: colors.surface,
            borderColor: colors.border,
            borderWidth: 1,
            borderRadius: borderRadius.full,
            paddingHorizontal: spacing.md,
            paddingVertical: spacing.xs,
            marginRight: spacing.sm,
            marginBottom: spacing.xs,
            minHeight: 34,
            justifyContent: "center" as const,
        }),
        [borderRadius, colors, spacing],
    );

    // ── Render ───────────────────────────────────────────────────────────────

    return (
        <>
            <BottomSheet
                ref={bottomSheetRef}
                index={-1}
                snapPoints={snapPoints}
                enableDynamicSizing={false}
                enablePanDownToClose
                onChange={handleSheetChange}
                onClose={handleSheetClose}
                handleIndicatorStyle={{
                    backgroundColor: colors.textMuted,
                }}
                backgroundStyle={{
                    backgroundColor: colors.surfaceElevated,
                }}
                keyboardBehavior="interactive"
                keyboardBlurBehavior="restore"
            >
                {isExpanded ? (
                    // ── FULL FORM ─────────────────────────────────────────────
                    <View style={styles.fullContainer}>
                        {/* Fixed header */}
                        <View
                            style={[
                                styles.formHeader,
                                {
                                    paddingHorizontal: spacing.lg,
                                    paddingBottom: spacing.sm,
                                    borderBottomColor: colors.divider,
                                },
                            ]}
                        >
                            <TouchableOpacity
                                onPress={handleCollapse}
                                style={styles.iconBtn}
                                testID="meal-form-collapse-btn"
                                accessibilityLabel={t("mealForm.btn_collapse")}
                            >
                                <Ionicons
                                    name="chevron-down"
                                    size={22}
                                    color={colors.textSecondary}
                                />
                            </TouchableOpacity>

                            <Text
                                style={[
                                    styles.headerTitle,
                                    {
                                        color: colors.textPrimary,
                                        fontSize: typography.fontSize.xl,
                                        fontWeight: typography.fontWeight.bold,
                                    },
                                ]}
                            >
                                {mode === "add"
                                    ? t("mealForm.title_add")
                                    : t("mealForm.title_edit")}
                            </Text>

                            <TouchableOpacity
                                onPress={handleClose}
                                style={styles.iconBtn}
                                testID="meal-form-close-btn"
                                accessibilityLabel={t("mealForm.btn_cancel")}
                            >
                                <Ionicons
                                    name="close"
                                    size={22}
                                    color={colors.textMuted}
                                />
                            </TouchableOpacity>
                        </View>

                        {/* Scrollable fields */}
                        <BottomSheetScrollView
                            style={styles.scrollArea}
                            contentContainerStyle={[
                                styles.scrollContent,
                                {
                                    paddingHorizontal: spacing.lg,
                                    paddingTop: spacing.md,
                                    paddingBottom: spacing.xxl,
                                },
                            ]}
                            showsVerticalScrollIndicator={false}
                            keyboardShouldPersistTaps="handled"
                        >
                            {/* Meal type chips */}
                            <Text style={sectionLabel}>
                                {t("mealForm.field_meal_type")}
                            </Text>
                            <View
                                style={[
                                    styles.chipRow,
                                    { marginBottom: spacing.md },
                                ]}
                            >
                                {MEAL_TYPES.map((type) => (
                                    <TouchableOpacity
                                        key={type}
                                        style={chipFor(mealType === type)}
                                        onPress={() => setMealType(type)}
                                        testID={`meal-form-type-${type}`}
                                        accessibilityLabel={t(
                                            `mealTypes.${type}`,
                                        )}
                                    >
                                        <Text
                                            style={{
                                                color:
                                                    mealType === type
                                                        ? colors.textOnAccent
                                                        : colors.textSecondary,
                                                fontSize:
                                                    typography.fontSize.sm,
                                                fontWeight:
                                                    mealType === type
                                                        ? typography.fontWeight
                                                              .semiBold
                                                        : typography.fontWeight
                                                              .regular,
                                            }}
                                        >
                                            {t(`mealTypes.${type}`)}
                                        </Text>
                                    </TouchableOpacity>
                                ))}
                            </View>

                            {/* Date + Time row */}
                            <View
                                style={[
                                    styles.dateTimeRow,
                                    {
                                        gap: spacing.md,
                                        marginBottom: spacing.md,
                                    },
                                ]}
                            >
                                {/* Date */}
                                <View style={styles.dateTimeCell}>
                                    <Text style={sectionLabel}>
                                        {t("mealForm.field_date")}
                                    </Text>
                                    <TouchableOpacity
                                        style={fieldRowButton}
                                        onPress={() => setShowDatePicker(true)}
                                        testID="meal-form-date-btn"
                                        accessibilityLabel={t(
                                            "mealForm.field_date",
                                        )}
                                    >
                                        <Ionicons
                                            name="calendar-outline"
                                            size={16}
                                            color={colors.textSecondary}
                                        />
                                        <Text
                                            style={{
                                                color: colors.textPrimary,
                                                fontSize:
                                                    typography.fontSize.md,
                                                flex: 1,
                                            }}
                                            numberOfLines={1}
                                        >
                                            {formatDisplayDate(selectedDate)}
                                        </Text>
                                    </TouchableOpacity>
                                </View>

                                {/* Time */}
                                <View style={styles.dateTimeCell}>
                                    <Text style={sectionLabel}>
                                        {t("mealForm.field_time")}
                                    </Text>
                                    <TouchableOpacity
                                        style={fieldRowButton}
                                        onPress={() => setShowTimePicker(true)}
                                        testID="meal-form-time-btn"
                                        accessibilityLabel={t(
                                            "mealForm.field_time",
                                        )}
                                    >
                                        <Ionicons
                                            name="time-outline"
                                            size={16}
                                            color={colors.textSecondary}
                                        />
                                        <Text
                                            style={{
                                                color: colors.textPrimary,
                                                fontSize:
                                                    typography.fontSize.md,
                                                flex: 1,
                                            }}
                                        >
                                            {selectedTime}
                                        </Text>
                                    </TouchableOpacity>
                                </View>
                            </View>

                            {/* Meal text */}
                            <View
                                style={[
                                    styles.fieldLabelRow,
                                    { marginBottom: spacing.xs },
                                ]}
                            >
                                <Text
                                    style={[sectionLabel, { marginBottom: 0 }]}
                                >
                                    {t("mealForm.field_meal_text")}
                                </Text>
                                <TouchableOpacity
                                    style={[
                                        styles.favoritesBtn,
                                        {
                                            backgroundColor: colors.surface,
                                            borderColor: colors.border,
                                            borderRadius: borderRadius.md,
                                            paddingVertical: 4,
                                            paddingHorizontal: spacing.sm,
                                            gap: 4,
                                        },
                                    ]}
                                    onPress={handleOpenFavoritesPicker}
                                    activeOpacity={0.8}
                                    testID="meal-form-full-favorites-btn"
                                    accessibilityLabel={t(
                                        "mealForm.btn_from_favorites",
                                    )}
                                >
                                    <Ionicons
                                        name="star-outline"
                                        size={13}
                                        color={colors.star}
                                    />
                                    <Text
                                        style={{
                                            color: colors.textSecondary,
                                            fontSize: typography.fontSize.xs,
                                        }}
                                    >
                                        {t("mealForm.btn_from_favorites")}
                                    </Text>
                                </TouchableOpacity>
                            </View>
                            <BottomSheetTextInput
                                multiline
                                onChangeText={(v) => {
                                    setMealText(v);
                                    if (validationError)
                                        setValidationError(null);
                                }}
                                placeholder={t(
                                    "mealForm.placeholder_meal_text",
                                )}
                                placeholderTextColor={colors.inputPlaceholder}
                                style={[
                                    styles.textInput,
                                    {
                                        backgroundColor: colors.inputBackground,
                                        borderColor: validationError
                                            ? colors.error
                                            : colors.inputBorder,
                                        borderRadius: borderRadius.md,
                                        color: colors.textPrimary,
                                        fontSize: typography.fontSize.md,
                                        marginBottom: spacing.xs,
                                        padding: spacing.md,
                                        minHeight: 80,
                                    },
                                ]}
                                testID="meal-form-meal-text-input"
                                textAlignVertical="top"
                                value={mealText}
                            />

                            {/* Recent meal suggestions */}
                            {filteredSuggestions.length > 0 && (
                                <View style={suggestionScrollContent}>
                                    {sortChipsByLength(
                                        filteredSuggestions.slice(
                                            0,
                                            MAX_SUGGESTIONS_FULL,
                                        ),
                                    ).map((s) => (
                                        <TouchableOpacity
                                            key={s}
                                            testID={`meal-form-suggestion-chip-${s}`}
                                            accessibilityLabel={s}
                                            onPress={() =>
                                                handlePickSuggestion(s)
                                            }
                                            style={suggestionChipStyle}
                                        >
                                            <Text
                                                numberOfLines={1}
                                                style={{
                                                    color: colors.textSecondary,
                                                    fontSize:
                                                        typography.fontSize.sm,
                                                    lineHeight: 18,
                                                }}
                                            >
                                                {s}
                                            </Text>
                                        </TouchableOpacity>
                                    ))}
                                </View>
                            )}
                            {validationError ? (
                                <Text
                                    style={{
                                        color: colors.error,
                                        fontSize: typography.fontSize.sm,
                                        marginBottom: spacing.sm,
                                    }}
                                >
                                    {validationError}
                                </Text>
                            ) : (
                                <View style={{ height: spacing.md }} />
                            )}

                            {/* Calories */}
                            <Text style={sectionLabel}>
                                {t("mealForm.field_calories")}
                            </Text>
                            <BottomSheetTextInput
                                keyboardType="number-pad"
                                onChangeText={setCalories}
                                placeholder={t("mealForm.placeholder_calories")}
                                placeholderTextColor={colors.inputPlaceholder}
                                style={[
                                    styles.singleLineInput,
                                    {
                                        backgroundColor: colors.inputBackground,
                                        borderColor: colors.inputBorder,
                                        borderRadius: borderRadius.md,
                                        color: colors.textPrimary,
                                        fontSize: typography.fontSize.md,
                                        marginBottom: spacing.md,
                                        padding: spacing.md,
                                    },
                                ]}
                                testID="meal-form-calories-input"
                                value={calories}
                            />

                            {/* User comment */}
                            <Text style={sectionLabel}>
                                {t("mealForm.field_comment")}
                            </Text>
                            <BottomSheetTextInput
                                multiline
                                onChangeText={setMealComment}
                                placeholder={t("mealForm.placeholder_comment")}
                                placeholderTextColor={colors.inputPlaceholder}
                                style={[
                                    styles.textInput,
                                    {
                                        backgroundColor: colors.inputBackground,
                                        borderColor: colors.inputBorder,
                                        borderRadius: borderRadius.md,
                                        color: colors.textPrimary,
                                        fontSize: typography.fontSize.md,
                                        marginBottom: spacing.md,
                                        padding: spacing.md,
                                        minHeight: 64,
                                    },
                                ]}
                                testID="meal-form-comment-input"
                                textAlignVertical="top"
                                value={mealComment}
                            />

                            {/* AI analysis notes */}
                            <Text style={sectionLabel}>
                                {t("mealForm.field_ai_notes")}
                            </Text>
                            <BottomSheetTextInput
                                multiline
                                onChangeText={setNotes}
                                placeholder={t("mealForm.placeholder_ai_notes")}
                                placeholderTextColor={colors.inputPlaceholder}
                                style={[
                                    styles.textInput,
                                    {
                                        backgroundColor: colors.inputBackground,
                                        borderColor: colors.inputBorder,
                                        borderRadius: borderRadius.md,
                                        color: colors.textPrimary,
                                        fontSize: typography.fontSize.md,
                                        padding: spacing.md,
                                        minHeight: 64,
                                    },
                                ]}
                                testID="meal-form-notes-input"
                                textAlignVertical="top"
                                value={notes}
                            />
                        </BottomSheetScrollView>

                        {/* Fixed footer — always visible above keyboard */}
                        <View
                            style={[
                                styles.footer,
                                {
                                    paddingHorizontal: spacing.lg,
                                    paddingTop: spacing.sm,
                                    paddingBottom: spacing.lg + insets.bottom,
                                    borderTopColor: colors.divider,
                                    gap: spacing.sm,
                                },
                            ]}
                        >
                            <TouchableOpacity
                                style={[
                                    styles.cancelBtn,
                                    {
                                        backgroundColor: colors.surface,
                                        borderColor: colors.border,
                                        borderRadius: borderRadius.md,
                                        paddingVertical: spacing.md,
                                    },
                                ]}
                                onPress={handleClose}
                                activeOpacity={0.85}
                                testID="meal-form-cancel-btn"
                                accessibilityLabel={t("mealForm.btn_cancel")}
                            >
                                <Text
                                    style={{
                                        color: colors.textPrimary,
                                        fontSize: typography.fontSize.md,
                                        fontWeight:
                                            typography.fontWeight.semiBold,
                                    }}
                                >
                                    {t("mealForm.btn_cancel")}
                                </Text>
                            </TouchableOpacity>

                            {mode === "edit" && (
                                <TouchableOpacity
                                    style={[
                                        styles.deleteBtn,
                                        {
                                            backgroundColor: colors.surface,
                                            borderColor: colors.error,
                                            borderRadius: borderRadius.md,
                                            paddingVertical: spacing.md,
                                        },
                                    ]}
                                    onPress={handleDelete}
                                    activeOpacity={0.85}
                                    testID="meal-form-delete-btn"
                                    accessibilityLabel={t(
                                        "mealForm.btn_delete",
                                    )}
                                >
                                    <Text
                                        style={{
                                            color: colors.error,
                                            fontSize: typography.fontSize.md,
                                            fontWeight:
                                                typography.fontWeight.semiBold,
                                        }}
                                    >
                                        {t("mealForm.btn_delete")}
                                    </Text>
                                </TouchableOpacity>
                            )}

                            <TouchableOpacity
                                style={[
                                    styles.saveBtn,
                                    {
                                        backgroundColor:
                                            isSaving || isAnalyzing
                                                ? colors.primaryMuted
                                                : colors.primary,
                                        borderRadius: borderRadius.md,
                                        paddingVertical: spacing.md,
                                    },
                                ]}
                                onPress={handleSave}
                                disabled={isSaving || isAnalyzing}
                                activeOpacity={0.85}
                                testID="meal-form-save-btn"
                                accessibilityLabel={t("mealForm.btn_save")}
                            >
                                <Text
                                    style={{
                                        color: colors.textOnAccent,
                                        fontSize: typography.fontSize.md,
                                        fontWeight: typography.fontWeight.bold,
                                    }}
                                >
                                    {isSaving
                                        ? t("mealForm.btn_saving")
                                        : isAnalyzing
                                          ? t("mealForm.analyzing")
                                          : t("mealForm.btn_save")}
                                </Text>
                            </TouchableOpacity>
                        </View>
                    </View>
                ) : (
                    // ── QUICK ENTRY ───────────────────────────────────────────
                    <BottomSheetView
                        style={[styles.quickContainer, { padding: spacing.lg }]}
                    >
                        {/* Header */}
                        <View
                            style={[
                                styles.formHeader,
                                {
                                    marginBottom: spacing.sm,
                                    borderBottomColor: colors.divider,
                                },
                            ]}
                        >
                            <Text
                                style={{
                                    color: colors.textPrimary,
                                    fontSize: typography.fontSize.xl,
                                    fontWeight: typography.fontWeight.bold,
                                    flex: 1,
                                }}
                            >
                                {mode === "add"
                                    ? t("mealForm.title_quick")
                                    : t("mealForm.title_edit")}
                            </Text>
                            <TouchableOpacity
                                onPress={handleClose}
                                style={styles.iconBtn}
                                testID="meal-form-quick-close-btn"
                                accessibilityLabel={t("mealForm.btn_cancel")}
                            >
                                <Ionicons
                                    name="close"
                                    size={22}
                                    color={colors.textMuted}
                                />
                            </TouchableOpacity>
                        </View>

                        {/* Meal text input */}
                        <BottomSheetTextInput
                            multiline
                            onChangeText={(v) => {
                                setMealText(v);
                                if (validationError) setValidationError(null);
                            }}
                            placeholder={t("mealForm.placeholder_meal_text")}
                            placeholderTextColor={colors.inputPlaceholder}
                            style={[
                                styles.textInput,
                                {
                                    backgroundColor: colors.inputBackground,
                                    borderColor: validationError
                                        ? colors.error
                                        : colors.inputBorder,
                                    borderRadius: borderRadius.md,
                                    color: colors.textPrimary,
                                    fontSize: typography.fontSize.md,
                                    marginBottom: spacing.xs,
                                    padding: spacing.md,
                                    minHeight: 90,
                                },
                            ]}
                            testID="meal-form-quick-input"
                            textAlignVertical="top"
                            value={mealText}
                        />

                        {/* Recent meal suggestions */}
                        {filteredSuggestions.length > 0 && (
                            <View style={suggestionScrollContent}>
                                {sortChipsByLength(
                                    filteredSuggestions.slice(
                                        0,
                                        MAX_SUGGESTIONS_QUICK,
                                    ),
                                ).map((s) => (
                                    <TouchableOpacity
                                        key={s}
                                        testID={`meal-form-suggestion-chip-${s}`}
                                        accessibilityLabel={s}
                                        onPress={() => handlePickSuggestion(s)}
                                        style={suggestionChipStyle}
                                    >
                                        <Text
                                            numberOfLines={1}
                                            style={{
                                                color: colors.textSecondary,
                                                fontSize:
                                                    typography.fontSize.sm,
                                                lineHeight: 18,
                                            }}
                                        >
                                            {s}
                                        </Text>
                                    </TouchableOpacity>
                                ))}
                            </View>
                        )}

                        {validationError ? (
                            <Text
                                style={{
                                    color: colors.error,
                                    fontSize: typography.fontSize.sm,
                                    marginBottom: spacing.sm,
                                }}
                            >
                                {validationError}
                            </Text>
                        ) : (
                            <View style={{ height: spacing.sm }} />
                        )}

                        {/* Favorites shortcut */}
                        <TouchableOpacity
                            style={[
                                styles.favoritesBtn,
                                {
                                    backgroundColor: colors.surface,
                                    borderColor: colors.border,
                                    borderRadius: borderRadius.md,
                                    paddingVertical: spacing.sm,
                                    paddingHorizontal: spacing.md,
                                    marginBottom: spacing.sm,
                                    gap: spacing.sm,
                                },
                            ]}
                            onPress={handleOpenFavoritesPicker}
                            activeOpacity={0.8}
                            testID="meal-form-quick-favorites-btn"
                            accessibilityLabel={t(
                                "mealForm.btn_from_favorites",
                            )}
                        >
                            <Ionicons
                                name="star-outline"
                                size={15}
                                color={colors.star}
                            />
                            <Text
                                style={{
                                    color: colors.textSecondary,
                                    fontSize: typography.fontSize.sm,
                                }}
                            >
                                {t("mealForm.btn_from_favorites")}
                            </Text>
                        </TouchableOpacity>

                        {/* Action row */}
                        <View style={[styles.actionRow, { gap: spacing.sm }]}>
                            <TouchableOpacity
                                style={[
                                    styles.expandBtn,
                                    {
                                        backgroundColor: colors.surface,
                                        borderColor: colors.border,
                                        borderRadius: borderRadius.md,
                                        paddingVertical: spacing.md,
                                        gap: spacing.xs,
                                    },
                                ]}
                                onPress={handleExpand}
                                activeOpacity={0.85}
                                testID="meal-form-expand-btn"
                                accessibilityLabel={t("mealForm.btn_expand")}
                            >
                                <Ionicons
                                    name="expand-outline"
                                    size={15}
                                    color={colors.primary}
                                />
                                <Text
                                    style={{
                                        color: colors.primary,
                                        fontSize: typography.fontSize.sm,
                                        fontWeight:
                                            typography.fontWeight.semiBold,
                                    }}
                                >
                                    {t("mealForm.btn_expand")}
                                </Text>
                            </TouchableOpacity>

                            <TouchableOpacity
                                style={[
                                    styles.quickSaveBtn,
                                    {
                                        backgroundColor:
                                            isSaving || isAnalyzing
                                                ? colors.primaryMuted
                                                : colors.primary,
                                        borderRadius: borderRadius.md,
                                        paddingVertical: spacing.md,
                                    },
                                ]}
                                onPress={handleSave}
                                disabled={isSaving || isAnalyzing}
                                activeOpacity={0.85}
                                testID="meal-form-quick-save-btn"
                                accessibilityLabel={t("mealForm.btn_save")}
                            >
                                <Text
                                    style={{
                                        color: colors.textOnAccent,
                                        fontSize: typography.fontSize.md,
                                        fontWeight: typography.fontWeight.bold,
                                    }}
                                >
                                    {isSaving
                                        ? t("mealForm.btn_saving")
                                        : isAnalyzing
                                          ? t("mealForm.analyzing")
                                          : t("mealForm.btn_save")}
                                </Text>
                            </TouchableOpacity>
                        </View>
                    </BottomSheetView>
                )}
            </BottomSheet>

            {/* Favorites picker modal */}
            <Modal
                visible={showFavoritesPicker}
                transparent
                animationType="slide"
                onRequestClose={() => setShowFavoritesPicker(false)}
                statusBarTranslucent
            >
                <TouchableOpacity
                    style={styles.modalBackdrop}
                    activeOpacity={1}
                    onPress={() => setShowFavoritesPicker(false)}
                    accessibilityLabel={t("mealForm.btn_cancel")}
                />
                <View
                    style={[
                        styles.modalSheet,
                        {
                            backgroundColor: colors.surfaceElevated,
                            borderTopLeftRadius: borderRadius.xl,
                            borderTopRightRadius: borderRadius.xl,
                            paddingBottom: insets.bottom,
                        },
                    ]}
                >
                    <View
                        style={[
                            styles.modalHeader,
                            {
                                paddingHorizontal: spacing.lg,
                                paddingVertical: spacing.md,
                                borderBottomColor: colors.divider,
                            },
                        ]}
                    >
                        <Text
                            style={{
                                color: colors.textPrimary,
                                fontSize: typography.fontSize.lg,
                                fontWeight: typography.fontWeight
                                    .bold as TextStyle["fontWeight"],
                                flex: 1,
                            }}
                        >
                            {t("mealForm.favorites_picker_title")}
                        </Text>
                        <TouchableOpacity
                            onPress={() => setShowFavoritesPicker(false)}
                            style={styles.iconBtn}
                            testID="favorites-picker-close-btn"
                            accessibilityLabel={t("mealForm.btn_cancel")}
                        >
                            <Ionicons
                                name="close"
                                size={22}
                                color={colors.textMuted}
                            />
                        </TouchableOpacity>
                    </View>
                    {favoritesSections.length === 0 ? (
                        <View style={styles.modalEmpty}>
                            <Text
                                style={{
                                    color: colors.textSecondary,
                                    fontSize: typography.fontSize.md,
                                    textAlign: "center",
                                }}
                            >
                                {t("mealForm.favorites_picker_empty")}
                            </Text>
                        </View>
                    ) : (
                        <SectionList
                            sections={favoritesSections}
                            keyExtractor={(item) => item.id.toString()}
                            contentContainerStyle={{
                                paddingVertical: spacing.sm,
                            }}
                            renderSectionHeader={({ section: { title } }) => (
                                <Text
                                    style={[
                                        sectionLabel,
                                        {
                                            paddingHorizontal: spacing.lg,
                                            paddingTop: spacing.sm,
                                        },
                                    ]}
                                >
                                    {title}
                                </Text>
                            )}
                            renderItem={({ item }) => (
                                <TouchableOpacity
                                    style={[
                                        styles.favoriteRow,
                                        {
                                            paddingHorizontal: spacing.lg,
                                            paddingVertical: spacing.md,
                                            borderBottomColor: colors.divider,
                                        },
                                    ]}
                                    onPress={() => handlePickFavorite(item)}
                                    activeOpacity={0.7}
                                    testID={`favorites-picker-item-${item.id}`}
                                    accessibilityLabel={item.name}
                                >
                                    <View style={styles.favoriteRowLeft}>
                                        <Ionicons
                                            name={
                                                item.type === "template"
                                                    ? "bookmark-outline"
                                                    : "star-outline"
                                            }
                                            size={16}
                                            color={
                                                item.type === "template"
                                                    ? colors.primary
                                                    : colors.star
                                            }
                                            style={{ marginTop: 2 }}
                                        />
                                        <View style={{ flex: 1 }}>
                                            <Text
                                                style={{
                                                    color: colors.textPrimary,
                                                    fontSize:
                                                        typography.fontSize.md,
                                                    fontWeight: typography
                                                        .fontWeight
                                                        .semiBold as TextStyle["fontWeight"],
                                                }}
                                                numberOfLines={1}
                                            >
                                                {item.name}
                                            </Text>
                                            <Text
                                                style={{
                                                    color: colors.textSecondary,
                                                    fontSize:
                                                        typography.fontSize.sm,
                                                    marginTop: 2,
                                                }}
                                                numberOfLines={2}
                                            >
                                                {item.mealText}
                                            </Text>
                                        </View>
                                    </View>
                                    {item.calories != null && (
                                        <Text
                                            style={{
                                                color: colors.secondary,
                                                fontSize:
                                                    typography.fontSize.sm,
                                                fontWeight: typography
                                                    .fontWeight
                                                    .bold as TextStyle["fontWeight"],
                                                marginLeft: spacing.sm,
                                            }}
                                        >
                                            {item.calories}{" "}
                                            {t("common.kcal_unit")}
                                        </Text>
                                    )}
                                </TouchableOpacity>
                            )}
                        />
                    )}
                </View>
            </Modal>

            {/* Native date picker */}
            {showDatePicker && (
                <DateTimePicker
                    value={datePickerValue}
                    mode="date"
                    display="default"
                    onChange={handleDateChange}
                />
            )}

            {/* Native time picker */}
            {showTimePicker && (
                <DateTimePicker
                    value={timePickerValue}
                    mode="time"
                    is24Hour
                    display="default"
                    onChange={handleTimeChange}
                />
            )}
        </>
    );
});

MealFormSheet.displayName = "MealFormSheet";

// ─── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
    fullContainer: {
        flex: 1,
    },
    quickContainer: {
        flex: 1,
    },
    formHeader: {
        flexDirection: "row",
        alignItems: "center",
        paddingTop: 4,
        borderBottomWidth: StyleSheet.hairlineWidth,
    },
    headerTitle: {
        flex: 1,
        textAlign: "center",
    },
    iconBtn: {
        padding: 6,
        minWidth: 34,
        minHeight: 34,
        alignItems: "center",
        justifyContent: "center",
    },
    scrollArea: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
    },
    chipRow: {
        flexDirection: "row",
        flexWrap: "wrap",
    },
    suggestionsScroll: {
        flexGrow: 0,
    },
    dateTimeRow: {
        flexDirection: "row",
    },
    dateTimeCell: {
        flex: 1,
    },
    textInput: {
        borderWidth: 1,
    },
    singleLineInput: {
        borderWidth: 1,
    },
    footer: {
        flexDirection: "row",
        borderTopWidth: StyleSheet.hairlineWidth,
    },
    cancelBtn: {
        flex: 1,
        alignItems: "center",
        borderWidth: 1,
    },
    deleteBtn: {
        flex: 1,
        alignItems: "center",
        borderWidth: 1,
    },
    saveBtn: {
        flex: 2,
        alignItems: "center",
    },
    actionRow: {
        flexDirection: "row",
        alignItems: "center",
    },
    expandBtn: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
    },
    quickSaveBtn: {
        flex: 2,
        alignItems: "center",
    },
    fieldLabelRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    favoritesBtn: {
        flexDirection: "row",
        alignItems: "center",
        borderWidth: 1,
    },
    modalHeader: {
        flexDirection: "row",
        alignItems: "center",
        borderBottomWidth: StyleSheet.hairlineWidth,
    },
    modalEmpty: {
        padding: 32,
        alignItems: "center",
    },
    favoriteRow: {
        flexDirection: "row",
        alignItems: "center",
        borderBottomWidth: StyleSheet.hairlineWidth,
    },
    favoriteRowLeft: {
        flex: 1,
        flexDirection: "row",
        alignItems: "flex-start",
        gap: 10,
    },
    modalBackdrop: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(0,0,0,0.5)",
    },
    modalSheet: {
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 0,
        maxHeight: "60%",
        overflow: "hidden",
    },
});
